#!/usr/local/bin/php
<?php

  $app = require __DIR__.'/bootstrap.php';

  $console = $app['console'];
  $console -> add(new thcolin\Gearman\Command\FireWorkerCommand);
  $console -> add(new thcolin\Gearman\Command\HireWorkerCommand);
  $console -> add(new thcolin\Gearman\Command\AddJobCommand);
  $console -> add(new thcolin\Gearman\Command\RunJobCommand);
  $console -> add(new thcolin\Gearman\Command\WatchJobCommand);
  $console -> add(new thcolin\Gearman\Command\DeleteJobCommand);
  $console -> run();

?>
